### ISSUE TITLE
Host GHC Docker Image on DockerHub

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#108]
Currently the GHC Docker Image is identified as `yjacolin/geohealthcheck` plus the Docker image needs to be built locally. It will be helpful for users to host the GHC Docker Image from DockerHub. The following needs to be done:

- rename image in GHC Dockerfile and docker-compose
- create GHC account (or org?) on DockerHub
- provide build automation such that a new Docker image is built/pushed on GH-commits
- provide Docker image versioning (tags), best to follow GHC versions + `latest` (default)
- possibly automatic Travis testing 
- more documentation how to deploy GHC using Docker

**Comment by justb4** [comment]
We have created a GeoPython org on Docker Hub. GHC Images are hosted from:
https://hub.docker.com/r/geopython/geohealthcheck/

**Comment by justb4** [comment]
Done

**Comment by yjacolin** [comment]
thanks! :)
