### ISSUE TITLE
Data export for individual resources (CSV and JSON)

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#11]
## User Story:
As a user
I want to export historical data for any individual resource monitored in JSON or CSV
so that I can use the output programmatically (JSON) or download for tabular analysis (CSV)

## Current situation
Data export is limited to the main list of resources. For example, given the monitoring site http://geohealthcheck.osgeo.org you can export data using http://geohealthcheck.osgeo.org/export

## Proposed changes
* See related issue for URL formatting (https://github.com/geopython/GeoHealthCheck/issues/10)
* allow export of historical data 
* allow export of current data

### Current Data
CSV: http://geohealthcheck.osgeo.org/resource/1/csv
JSON: http://geohealthcheck.osgeo.org/resource/1/json

* Type
* Owner
* Name
* URL
* Response_time
* Last_Tested
* Status
* hist_csv  = http://geohealthcheck.osgeo.org/resource/1/history/csv
* hist_json = http://geohealthcheck.osgeo.org/resource/1/history/json

### Historical data
CSV: http://geohealthcheck.osgeo.org/resource/1/history/csv
JSON: http://geohealthcheck.osgeo.org/resource/1/history/json

* Type
* Owner
* Name
* URL
* Date
* Response Time
* Status

**Comment by tomkralidis** [comment]
implemented in master

**Comment by samperd** [comment]
Looks Good.

Some of the suggested attributes listed above are not implemented. But is it great to have the data in the two formats

**Comment by samperd** [comment]
Missing in JSON

hist_csv = http://geohealthcheck.osgeo.org/resource/history/1/csv
hist_json = http://geohealthcheck.osgeo.org/resource/history/1/json (equivalent self link)
      
Missing in CSV
CSV: http://geohealthcheck.osgeo.org/resource/history/1/csv (equivalent self link)
JSON: http://geohealthcheck.osgeo.org/resource/history/1/json
