### ISSUE TITLE
Show simple health trend chart on resources table

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#12]
## User Story:
As a user
I want to see a small line chart to visualize health trend of all resources over time
So I can quickly examine and compare all resources on the main page.

## Current situation
Given a monitoring page such as: http://geohealthcheck.osgeo.org/:
* Type, name, last check, status, response time, reliability already exist.

## Proposed
* insert a new column displaying a line chart of access for the last week/month/quarter/year (configurable, default week).
* provide chart using dots 
** 7 - 14 = last week (dot=day)
** 4 = last month (dot = week)
** 12 = last quarter (dot = week)
** 52 = annual (dot =week)

* dots represent lowest status for that day/week. For example if nothing failed( green), if one yellow then use yellow, if red then put dot red.
* For the Y axis, use the AVERAGE of the response time for the day/week

## Example
Check out the dashboard for PIWIK here: http://demo.piwik.org/index.php?module=MultiSites&action=index&idSite=3&period=day&date=yesterday
* notice the last collumn wihc is a small graphic. I am proposing something similar

**Comment by tomkralidis** [comment]
@samperd implemented sparklines in c40804aaa920c2ac8dd877607d39d0cc67d63a4d. Can you verify and close if this works for you?

**Comment by hannesaddec** [comment]
works for me. Propose to close it
