### ISSUE TITLE
Issues in Windows during paver setup

### ISSUE THREAD

**Issue by josegar74** [geopython/GeoHealthCheck#126]
`paver setup` fail in Windows due to following lines:

https://github.com/geopython/GeoHealthCheck/blob/master/pavement.py#L226-L228

The line ` sh('mkdir %s' % options.base.static_docs)` fails due to mixup of different slashes:

```
Build finished. The HTML pages are in _build/html.
mkdir C:\Users\XXXXX\GeoHealthCheck/GeoHealthCheck/static/docs
The syntax of the command is incorrect.
```

Changing this line https://github.com/geopython/GeoHealthCheck/blob/master/pavement.py#L50 

`static_docs=path('%s/GeoHealthCheck/static/docs' % BASEDIR),`

to this fixes it:

` static_docs=path('%s' % BASEDIR + os.sep + 'GeoHealthCheck' + os.sep + 'static' + os.sep + 'docs' ),`

But probably there's a more elegant way to change this.

The line https://github.com/geopython/GeoHealthCheck/blob/master/pavement.py#L227 fails due to `cp` not available in Windows. I guess this could be changed to use `shutil.copy`?

**Comment by justb4** [comment]
Hi @josegar74 . Yes I see that several aspects of [pavement.py]( https://github.com/geopython/GeoHealthCheck/blob/master/pavement.py) need to be made OS-independent. Would be nice if you could help us with patches/PRs. I found some examples like here:  https://github.com/geopython/GeoHealthCheck/blob/master/pavement.py where both path-concatenation using Pavement `path` and dir-copying is handled e.g. `html_docs.copytree(doc_root / "html")`. We could use similar expressions.

**Comment by josegar74** [comment]
Sounds good, will check to improve this and submit a pull request for review.

**Comment by justb4** [comment]
Hi @josegar74 , has this been resolved, can we close?

**Comment by josegar74** [comment]
@justb4 unfortunately I don't have resources for now to work in this. Possibly if my customer is interested later, will also move to a Linux environment, so not relevant anymore. I think you can close it.

**Comment by justb4** [comment]
Ok thanks @josegar74 . Hmm I now see that the Pythonic way is to use `os.path.join(dir, <multi-args>)` so 

```
static_docs=path('%s/GeoHealthCheck/static/docs' % BASEDIR),
```
should become something like 

```
static_docs=os.path.join(%s, 'GeoHealthCheck', 'static', 'docs') % BASEDIR

```

So I will leave open and fix this.

**Comment by justb4** [comment]
Note to self:  IMO cleaner to use `pathlib`s `Path` as is standard in Python3 and lib in Python2:
https://www.scivision.co/python-idiomatic-pathlib-use/

**Comment by justb4** [comment]
@josegar74 maybe have time for trying a windows install so we can hopefully close?

**Comment by justb4** [comment]
Issue has been open for 2 year+, no final feedback, closing, @josegar74 please re-open if still a problem, ok?
