### ISSUE TITLE
Link to Health Check project from Geopython page is dead

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#13]
On the page: http://geopython.github.io/

The health check URL should be changed
From: http://geopython.github.io/GeoHealthCheck
To: https://github.com/geopython/GeoHealthCheck

**Comment by tomkralidis** [comment]
@samperd thanks.  FYI the docs are at https://github.com/geopython/GeoHealthCheck/blob/master/docs/index.rst .  I'll set this up in the next day or two and then the docs will publish and the link will work.  BTW any doc additions / updates are welcome!

**Comment by tomkralidis** [comment]
docs publishing now implemented in master.

**Comment by samperd** [comment]
I confirm the link now works.

Thanks @tomkralidis
