### ISSUE TITLE
Allow setting resource-specific testing frequency

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/GeoHealthCheck#132]
Feature request to be able to specify a different testing frequency for resources.

Example: I'd like GHC to test a WMS server every 10 minutes and another WMS server every 6 hours.

**Comment by justb4** [comment]
Very useful feature! Already before discussed with @tomkralidis. Impact on the current cron/jobber-based architecture: thinking of a "daemon" based testrunner with multithreading with Schedules attached to Resources, (or Probes) in DB. Useful also, as some of the new Probes may take several minutes to execute e.g. probing all Layers of a WMS.

**Comment by justb4** [comment]
Did some recent comments disappear?

**Comment by alexandreleroux** [comment]
@justb4 I don't think so, not according to the emails notifications I got

**Comment by justb4** [comment]
@alexandreleroux sorry, wrong issue, was in #135 I opened, "big WMSs" impact check frequency as well, hence my thinking...

**Comment by justb4** [comment]
@tomkralidis @ingenieroariel What we really need is a "daemon" process for the Runner part (the web/Flask part is already daemonized by its WSGI/webserver). This is OS-specific. A Python lib like https://pypi.python.org/pypi/python-daemon/ IMHO does not provide this. For example for Debian-flavors we can use and `initd` daemon like described here:
http://blog.scphillips.com/posts/2013/07/getting-a-python-script-to-run-in-the-background-as-a-service-on-boot/. So we could provide something like the above (with a Debian/UbuntuGIS package). For Docker deployments the above is less of a problem IMO. 

The most flexible is to provide 3 modes of running the Runner-part:

* as currently: hourly `cron` job
* within the Flask webapp (APscheduler will run in background) --> may risk overloading webserver.
* using a separate daemon process (see above)

**Comment by justb4** [comment]
First version of the new ways of running the GHC Healthchecks: 

- old way using `cron` (deprecated)
- new way running two processes (Web and Runner)
- new way running Web and Runner in single process

The last one can be tested using the Docker image built from the branch for this issue (`per_resource_scheduling`):

```
docker run  --name ghc_web -e GHC_RUNNER_IN_WEBAPP=True -e GHC_LOG_LEVEL=10 -v ghc_sqlitedb:/GeoHealthCheck/DB geopython/geohealthcheck:per_resource_scheduling
```

The ENV setting `GHC_RUNNER_IN_WEBAPP=True` will activate spawning the `GHC Runner` within the Webapp. Test frequency per Resource can be scheduled via the Dashboard.

The most stable is to use the `docker-compose` configs: see the [README there](https://github.com/geopython/GeoHealthCheck/blob/per_resource_scheduling/docker/README.md).

**Comment by justb4** [comment]
@alexandreleroux agree to close? #222 implemented resource-specific testing frequency. We can proceed in maintenance mode.

**Comment by alexandreleroux** [comment]
Thanks @justb4 , agreed, closing. 
Shouldn't https://github.com/geopython/GeoHealthCheck/pull/175 be closed as well now?

**Comment by justb4** [comment]
On 05-11-18 20:06, Alexandre Leroux wrote:
> Thanks @justb4 <https://github.com/justb4> , agreed, closing.
> Shouldn't #175 <https://github.com/geopython/GeoHealthCheck/pull/175> be 
> closed as well now?

Good suggestion, done!
