### ISSUE TITLE
Send email notifications on a per-resource basis

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/GeoHealthCheck#134]
Feature request: capability to configure and send email notifications on a per-resource basis

Example: for WMS server 'A', I want email notifications to be sent to foo@bar.org and for WMS server 'B', sent to bar@foo.org

**Comment by justb4** [comment]
Looks like a subset of issue #15. Also previously requested by @archaeogeek via issue #88 (channeled into #15). We need to reconsider the email notification strategy in general (default/global notification email(s), override/add per Resource etc). As a first step one or more notification emails can be configured for a single GHC instance. Ok to channel this issue into #15 and work from there?

**Comment by alexandreleroux** [comment]
Thanks @justb4 , I didn't notice it was contained in #15. Closing.
