### ISSUE TITLE
Resource URL metadata not always visible in Probe forms

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#135]
As per issue #125 we started to populate several `Probe` GUI Forms from metadata ("Capabilities") acquired via `OWSLib` from a `Resource` URL endpoint, e.g. selecting a `WMS Layer` or `WFS FeatureType` via a dropdown/combo-box. In cases this doesn't work as expected: some form elements remain empty or get data from a previous `Probe`. For now emptying your browser-cache and reloading helps, but this needs to be fixed more structurally. Also, when URL endpoints contain many Layers/FeatureTypes, performance is impacted, and even time-outs are observed (running with `gunicorn` with async handlers `eventlet` or `greenlet` helps though). 

In general there may be a "Python global class data" issue with in the `Probe` class `PARAMs` here that needs to be resolved first.

**Comment by hannesaddec** [comment]
On the many layers issue.. the maximum of layers in one server I observed where 800, some arcgis server became unstable after 2xx layers.

**Comment by alexandreleroux** [comment]
Here's a [WMS server with currently over 1,400 layers](http://geo.weather.gc.ca/geomet-beta?service=WMS&version=1.3.0&request=GetCapabilities) and it's stable (and it's not Esri) ;-)

**Comment by justb4** [comment]
Yes, seen those cases as well, impacting interworking with OGC-clients in many contexts, not just GHC. With e.g. GeoServer one can define [Virtual Services](http://docs.geoserver.org/latest/en/user/configuration/virtual-services.html) to divide all Layers/FeatureTypes into meaningful subsets (i.e.  multiple WMSs/WFSs), and have a separate metadata/CSW to describe/search these subsets as separate service endpoints. This is the way the [National GDI within The Netherlands](https://www.pdok.nl/nl/producten/pdok-services/overzicht-urls) is organized. More than 10/20 Layers in a WMS is already questionable (how would you describe a 200+ layers WMS metadata?, "all stuff"?). 

But we have to deal with these cases. One solution (for GHC) I was thinking about is to cache `Capabilities`, at least for some time. It is undoable to request and process Caps from those "bulky" endpoints for each  and every GHC GUI action...

**Comment by justb4** [comment]
Also added caps-caching (expiry in 2 hours).

**Comment by tomkralidis** [comment]
Can we make capabilities caching a configurable value?

**Comment by justb4** [comment]
+1, but then more generic as part of `Resource` (caching is now tied to `Probe`). It now gives a tremendous performance boost for URLs with 50+ Layers...
