### ISSUE TITLE
Windows users need to run dos2unix on install.sh

### ISSUE THREAD

**Issue by bart-simci** [geopython/GeoHealthCheck#143]
When running docker build /path/to/GeoHealthCheck docker gives: '\r': command not found 
To avoid this, run dos2unix docker/install.sh to convert line endings in place to something windows understands.

**Comment by justb4** [comment]
This is strange, I cannot find any ``\CR\LF`` line endings in any of the `*.sh` docker script files, e.g. (`$` denotes ``\LF``, no `^M` is shown. If this was the case then the Docker Hub automatic build would not work. Are you sure this is not related to your local environment (your `.gitattributes` file) ? See e.g. https://help.github.com/articles/dealing-with-line-endings/

```
nusa:docker just$ cat -e install.sh 
#!/bin/bash$
$
cd /$
virtualenv venv && cd $_$
. bin/activate$
$
# GHC Source was ADDed in Dockerfile$
cd /GeoHealthCheck$
pip install Paver$
pip install sphinx$
$
# For PostGIS support$
pip install psycopg2$
$
# For WSGI server$
# NB we use async workers as some Probes may take a long time$
# e.g. fetching Metadata (Caps) and testing all layers$
pip install -I eventlet$
pip install -I gunicorn$
$
# Sets up GHC itself$
paver setup$
mv /config_site.py /GeoHealthCheck/instance/config_site.py$
$
# Copy possible Plugins into app tree$
if [ -d /plugins ]$
then$
	# Copy possible Plugins into app tree$
	cp -ar /plugins/* GeoHealthCheck/plugins/$
$
	# Remove to allow later Volume mount of /plugins$
	rm -rf /plugins$
fi$
$
```
See https://stackoverflow.com/questions/3569997/view-line-endings-in-a-text-file how to show.

**Comment by bart-simci** [comment]
@justb4 I encountered it later in another docker setup as well. It took me some digging, but especially *.sh files are causing trouble. The good news is, it's not because of your code, but because of the GIT client on Win10. The conversion happens after pulling it in on my end. See [here](https://github.com/docker/labs/issues/215). So, not a bug. Sorry for that, but I was at loss yesterday. "Thankfully" it also happened on other docker projects.
