### ISSUE TITLE
Port the code to python3 and/or python2-3 compatible code

### ISSUE THREAD

**Issue by jorgejesus** [geopython/GeoHealthCheck#155]
Current code is only python2 compatible.

Possibility:
- Change code to python3 and only use python3
- Change code to be python2.7 and python3.3 compatible
- PyPy ??? (https://pypy.org/) (this could be hard)

Tools/Docs:
http://python-future.org/
Testing different possibility with tox:
https://tox.readthedocs.io/en/latest/

**Comment by jorgejesus** [comment]
Extra docs and explanation how to processed with extra tools
https://docs.python.org/3/howto/pyporting.html

**Comment by justb4** [comment]
Welcomed. I just did the reverse: Python3 project also supporting Py2: https://github.com/schettino72/sqla_yaml_fixtures/issues/1 what especially helped is more thorough tests, CI and code coverage (even went to 100% code coverage, but ok small project). GHC has some tests now but not exhaustive, so we should work on that as well to make the transition smoother.

**Comment by tomkralidis** [comment]
Update: following discussion on Gitter, given the 0.6.0 release we will update master to be Python 3 only moving forward.

**Comment by justb4** [comment]
@tomkralidis @borrob @jorgejesus 
Like many projects as Django (2.0 is PY3 only) etc, I would prefer not to have simultaneous Py2 and Py3 support, given that:

* Py2 will be EOL very soon (less than a year)
* maintenance: we already have limited human resources
* many users (more and more) are deploying with Docker

Like [with Stetl in a similar PR](https://github.com/geopython/stetl/pull/81) we decided to:

* bring out one last Py2 release (and Docker Image)
* make a branch of that release, for urgent fixes only
* bring out fresh Py3-only version

**Comment by borrob** [comment]
I'm working on the conversion to python3 (but somehow I can't assign this task to myself). I'm using the version that comes standard with `buster` (I believe that is `3.7.2`), but so far I think any '3' version will do.

I am aiming for a py3-only version, so as to keep the code as clean and simple as possible.

**Comment by tomkralidis** [comment]
I've added you as a collaborator so you should be able to assign yourself now - can you let me know if it works?

Agree, py3-only version.  We can cut a last released for Python 2 support when ready to merge the Python 3 work.

**Comment by justb4** [comment]
Sorry did not see this last comment. @borrob should be able to assign himself as test. great! we'll be there to support.

**Comment by borrob** [comment]
As a quick update: still working on the conversion. I think I addressed most of the issues now and currently I am fixing the docker build (that is having issues with importing).

**Comment by borrob** [comment]
Pull Request #280 is out. That should bring the codebase to python3.

**Comment by borrob** [comment]
Pull request #280 is merged to master, so I am closing this issue :)
