### ISSUE TITLE
Override TITLE Attribute for CSW services

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#16]
## User Story
As a user 
I would like to provide or override the TITLE attribute of CSW (or other OWS) service when it is missing
So that I can still monitor a service that I have no control over but might have a stake in 

## Example
My organization publishes data to an external catalog. 
I want to ensure that catalog is running because it hosts my data
I have no control over the config, but still want it tracked in GeoHealthChecker

## Proposal
If upon first submitting a GetCapabilities, the title attribute is empty, prompt user for an alternative title so entry can be saved in DB despite being a poorly managed CSW (or nay OWS service actually)

**Comment by tomkralidis** [comment]
You can already to this; if you are logged as as admin or the resource owner, you will see an 'Edit' button on the resource's page beside the 'Name' attribute.

**Comment by samperd** [comment]
I see the edit feature AFTER the resource has been added. The challenge I had was trying to add a WMS when the GetCapabilities document did not contain a TITLE element. Adding this resource failed, which means I could not go and edit the TITLE. This proposal is to allow the addition of TITLE for poorly populated GetCapability documents. Especially checking the health of services that are legacy and no one is maintaining or updating.

**Comment by tomkralidis** [comment]
Implemented in master.  Should work now?

**Comment by samperd** [comment]
works now....
