### ISSUE TITLE
enhancement suggestion- add option to disable a resource

### ISSUE THREAD

**Issue by archaeogeek** [geopython/GeoHealthCheck#161]
I would like to option to disable a resource, eg to stop checking it, without actually deleting it. The scenario is for resources that I know are going to be taken down for a period of time. I assume this could be implemented by adding an additional field in the database for active/inactive and then providing a checkbox in the web interface.

**Comment by tomkralidis** [comment]
@archaeogeek this is now in master branch. Can you test/verify?

**Comment by archaeogeek** [comment]
Thanks for the speedy response! It looks good so far, I can confirm that I can see the "Active" checkbox in the interface. I've got a resource in, but marked as inactive, so if I get any notifications about it I will raise that as another issue. Otherwise I'm happy to close this.
