### ISSUE TITLE
Provide "Total" Count of all services monitored

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#17]
## User Story
As a user or admin
I want to have a "total resources" count
So that I can quickly report on how many services are tracked.

## Observations
* given a health checker such as: http://geohealthcheck.osgeo.org/
* each resource type already has a count in brackets
* adding in my head gets hard when I start pushing 50+ resources spread across a number of types

## Proposal
* Just add up these counts into a total count.
* perhaps this info can also be included in the JSON / CSV export

**Comment by tomkralidis** [comment]
Implemented in master.

**Comment by samperd** [comment]
Looks great.

Thanks @tomkralidis
