### ISSUE TITLE
Problem with adding a WCS service

### ISSUE THREAD

**Issue by simboss** [geopython/GeoHealthCheck#174]
Opening this for reference.

I am trying to add a WCS Service from GeoServer but I am getting problems.

The server URL is [this](http://oda.dlr.de/geoserver/evoodas/ows?service=WCS&version=2.0.1&request=GetCapabilities).

**Comment by justb4** [comment]
@simboss (hi!) first make sure you entered the root URL http://oda.dlr.de/geoserver/evoodas/ows (not the Caps URL)? I tried on [GHC demo server](http://demo.geohealthcheck.org/) and did not see a problem:

![image](https://user-images.githubusercontent.com/582630/32341089-c6339b1a-bffc-11e7-80ca-153e94f38626.png)

Or did you try on another installation?

**Comment by justb4** [comment]
@simboss has this been solved for you?

**Comment by justb4** [comment]
Think issue resolved, so closing. @simboss pls reopen if still an issue.
