### ISSUE TITLE
docker-compose.yml version problem

### ISSUE THREAD

**Issue by MarcoDuiker** [geopython/GeoHealthCheck#179]
In my docker-compose (version 1.6.0, build d99cad6) the command 
`docker-compose -f docker-compose.yml up` gives the following error:
>ERROR: Version in "./docker-compose.ori.yml" is unsupported. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Changing line two to:
`version: "2"`

Solves the error.

**Comment by justb4** [comment]
You run quite an old version of docker-compose (and maybe Docker)? 
See https://docs.docker.com/compose/compose-file/compose-versioning/, is it possible that you upgrade to compose v3+?
In many cases a `docker-compose.yml` serves as an example to be adapted locally.
