### ISSUE TITLE
HTTP POST Resource URL with body gives an error after first use

### ISSUE THREAD

**Issue by MarcoDuiker** [geopython/GeoHealthCheck#182]
I am using the `HTTP POST Resource URL with body - by GHC Team` probe from the docker setup as referenced in the docs (gives me GHC 0.4-dev).

Setting the probet up proved to be no problem. I've copied a body into the body field, 

>`<?xml version="1.0" encoding="UTF-8"?> <GetFeature xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/2.0/wfs.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/wfs/2.0"  outputFormat="application/json"  service="WFS" version="2.0.0"><Query xmlns:app="http://www.deegree.org/app" typeNames="freshem:profielen"><fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0"             xmlns:gml="http://www.opengis.net/gml/3.2"             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"             xsi:schemaLocation="http://www.opengis.net/fes/2.0 http://schemas.opengis.net/filter/2.0/filterAll.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd"><fes:DWithin><fes:ValueReference>wkb_geometry</fes:ValueReference><gml:Point gml:id="P1" srsName="urn:ogc:def:crs:EPSG::28992"><gml:pos>45799.69726690774 391119.2508424872</gml:pos></gml:Point><fes:Distance uom="m">35.36</fes:Distance></fes:DWithin></fes:Filter></Query></GetFeature>`

 And pasted the expected response in the check "Response contains strings". This setup ran once resulting in a "succes: True". 

Since then it returns  "succes: False". with an error: 
>ERROR: Perform_request Err: AttributeError 'HttpPost' object has no attribute 'content_type'

Furthermore, each new probe I set up in this way gives the same error.

**Comment by justb4** [comment]
Difficult to say: WFS POSTing is problematic in its own sense. The `success: True` could be if you had not saved the `Probe`. Does this POST work with a general POST client like `Postman`? Without the WFS URL it is also hard to debug for me, or is it internal?

**Comment by MarcoDuiker** [comment]
The request works fine when send by Python using the requests module.
It seems that the error is comming from GHC itself and not from the service. Or am I reading the error wrongly?

**Comment by justb4** [comment]
Confirmed: used to work before but parameter handling has been changed and not all Probes updated. Tested ok with your payload: 2 Features in `FeatureCollection` returned.

You can test using the Docker Image `geopython/geohealthcheck:dev` whose build should be ready soon (is automated on commits). Keep checking `dev` tag on https://hub.docker.com/r/geopython/geohealthcheck/tags/ . This reflects the GitHub GHC `dev` branch. Once you confirm it is working this commit will be merged to `master` (which is reflected in `latest` Docker image).

**Comment by MarcoDuiker** [comment]
Thank you.

It is working.
