### ISSUE TITLE
use separate configuration when running tests

### ISSUE THREAD

**Issue by cezio** [geopython/GeoHealthCheck#188]
Currently tests are run with the same settings as running instance. This will cause data damage. Test runner should init app with separate settings.

**Comment by justb4** [comment]
True. We need a separate test env. One of the reasons currently was to be able to test with both sqlite and Postgres. We may even reuse the standard config and override just the DB-settings, like: http://flask.pocoo.org/docs/0.12/config/

**Comment by borrob** [comment]
Solved with merge #308 -> close issue.
