### ISSUE TITLE
Checks appended to all probes

### ISSUE THREAD

**Issue by mkofahl** [geopython/GeoHealthCheck#191]
Found a problem when adding checks to probes. Steps to reproduce:
- add a WMS or WMS resource
- remove all probes
- add a GetCapabilities probe (including the three default-checks)
- add a HttpGet+query probe 
- add a "Has specific Content-Type" check to the HttpGet+query probe
- save
- monitor the /update request

Result: the "Has specific Content-Type" check is also set for the GetCapabilities probe.

I tried to find out why this happens and came to https://github.com/geopython/GeoHealthCheck/blob/eeef4d7e0c2a63f58afcf83fd9f81c03fcba82ee/GeoHealthCheck/templates/edit_resource.html#L239

`$('.check-edit-forms')` returns all probes.

**Comment by mkofahl** [comment]
Should be something like 
   `$('.resource-probe-data[probeClass="' + check_class + '"] .check-edit-forms')` 
I guess?

**Comment by justb4** [comment]
Confirmed: @mkofahl thanks for the clear report! Also happens in other scenarios, e.g. when adding a `Probe` and `Check` and also before PR #187. Will investigate with your suggestions.

**Comment by justb4** [comment]
Should be fixed now, also verified on http://demo.geohealthcheck.org (runs master branch). 
@mkofahl can you verify and close if ok?

**Comment by mkofahl** [comment]
looks fine, successfully tested
