### ISSUE TITLE
Improve french translation

### ISSUE THREAD

**Issue by Lukos92** [geopython/GeoHealthCheck#195]
Hi,
Thanks for your project !
 
I purpose a new version of the file translations/fr/LC_MESSAGES/messages.po:
[messages.po.txt](https://github.com/geopython/GeoHealthCheck/files/1813425/messages.po.txt)

NOTICE: I have changed too some line numbers whose seem to be false! There are the same errors in the English version!?!
Lukos92

**Comment by justb4** [comment]
@Lukos92 thanks for this! Is it possible that you provide us a Pull Request (PR) for these changes?

**Comment by Lukos92** [comment]
Hi, Just! Of course I can. But I am not very familiar with GitHub...

But, what about the changes in line numbers of localized terms that i have changed ? Do you have encounter problems with the English version ?  See the differences for edit_resource.html...

Lukos92

**Comment by justb4** [comment]
@Lukos92 that's ok. Probably best to start with some GitHub tutorials and then "PRs".

I will for now take your file and add to the French translation and look for issues in line numbers.
Maybe because the default language is English we did not see a problem.
There is still an [open issue on translations](https://github.com/geopython/GeoHealthCheck/issues/150) in general.

**Comment by justb4** [comment]
@Lukos92 Ok, I have committed your translations to the "dev" branch. Can you check at the URL:

http://dev.geohealthcheck.org/add?lang=fr

and if ok,  can you close this issue? We can work on the  "line numbers problem" via issue #150.

**Comment by Lukos92** [comment]
Ok Just. I use to do Merge Request on GitLab. So, it seems to be the same
kind of action.

I hope that I can create a new branch and pull request for merge tonight.

Lukos92

**Comment by justb4** [comment]
@Lukos92 no need for a PR right now: I had committed/pushed your file already to the `dev` branch, see:
https://github.com/geopython/GeoHealthCheck/blob/dev/GeoHealthCheck/translations/fr/LC_MESSAGES/messages.po

Your other question: the line numbers in the `.po` files are not important, they are in comments and generated the first time by `Babel`. So don't worry about them. Only the `msgid` and `msgstr` are important.

**Comment by justb4** [comment]
Closing, pls reopen if still unfinished.
