### ISSUE TITLE
add project to OSGeo pages

### ISSUE THREAD

**Issue by tomkralidis** [geopython/GeoHealthCheck#199]
Add GHC as a listed project on osgeo.org.  Initial page at https://www.osgeo.org/projects/geohealthcheck/

**Comment by justb4** [comment]
@tomkralidis Tried to edit the related WP Post after logging in on the OSGeo website, but possibly need password or so? When doing Edit or Quick Edit the Post was empty, or is there some other way?

Wanted to add some links (docs, GHC, demo etc) because there are none.  If you can do this and we can close this issue all the better.

**Comment by tomkralidis** [comment]
I have these setup already (https://www.osgeo.org/wp-admin/post.php?post=7178&action=edit) but can't seem to see them in the output page.  I've inquired (on OSGeo Slack) and waiting on response.

**Comment by tomkralidis** [comment]
Page updated (thanks @jodygarnett for help).

**Comment by jodygarnett** [comment]
Under the "end user resources" tab, add new row, type in the URL, select an appropriate icon and hit update?

**Comment by justb4** [comment]
Thanks @jodygarnett below my screenshot, I can only update some tags on RHS:

![image](https://user-images.githubusercontent.com/582630/49004559-c7729900-f164-11e8-8125-bb59502745f5.png)

**Comment by jodygarnett** [comment]
Right, you need to get the correct permissions for editing stuff on the website. Initially we had everything open but the discussion list was concerned :)

Can I ask you for your osgeo userid, and what roles you need?

reference: https://wiki.osgeo.org/wiki/Website <-- lists roles

**Comment by justb4** [comment]
Thanks @jodygarnett ! Yes, I can now edit all tabs etc. Extended some stuff. Was missing some things: 

* Communication|Social Media: we and possibly other projects use Gitter, no entry/logo.
* OGC Standards: added STA (SensorThings API) but could only add the abbrev, possibly WFS-FES (WFS3) deserves a separate entry as well

But possibly these points are for the OSGeo website GitHub.

For now author Role is fine, as chair of OSGeo.nl I see can add Events. I get back if I need more :-).

@tomkralidis if Post content fine with you we can close this issue.
