### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by dracic** [geopython/GeoHealthCheck#201]
Some parts of web gui are still hardcoded, I will try to make corrections in next few days and make PR. 

Also, as I can see, translations weren't recompiled on demo ghc page so some of  strings like "Select a link on the left to view Resources.", "Failing Resources" on home page etc. aren't translated when changing languages. I had to do another 'paver setup' on my GHC to correct this. Is this the proper way to do?

**Comment by justb4** [comment]
Thanks @dracic ! When adding a new language or updating a language `.po` file only some `PyBabel` commands are required. These can be called via `Paver`:

* `paver compile_translations` : compile all language files `.po` to `.mo`
* `paver update_translations` : think only updates line numbers in comments

Do `paver --help` for options.

The demo page does currently not update translations, we are working (#196) on improving deployment-on-commit.

**Comment by justb4** [comment]
Hi @dracic ! All updated language `.po` files from `paver update_translations` are now in master branch.
This means that missing translations have an empty `msgstr`. It is now a matter to fill in for each language, for you e.g. in https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/translations/hr_HR/LC_MESSAGES/messages.po if you have time...

And off course where hardcoded english is in the GUI we are happy with a PR :-).

**Comment by justb4** [comment]
@dracic there is now auto-build/deploy on master branch commit at https://demo.geohealthcheck.org (runs with Docker) including translations. Also some hardcoded english phrases were put in translations. Also all language files were updated for (missing) message strings, so https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/translations/hr_HR/LC_MESSAGES/messages.po is still waiting to be filled in...If you have time for a PR?

**Comment by justb4** [comment]
@dracic you can close if issue soved for you.

**Comment by dracic** [comment]
Looks good. Thanks @justb4 ...
