### ISSUE TITLE
False-positive results for WWW:LINK when outdated ssl libraries used

### ISSUE THREAD

**Issue by archaeogeek** [geopython/GeoHealthCheck#202]
Seen in Ubuntu 14.04 (python 2.7 virtual environment, gunicorn, supervisor, nginx). Initial creation of the resource (which uses owslib) works, but subsequent checks (which use requests) fail eg with  "HTTP Error status=500". @justb4 has done some digging (see gitter discussion at https://gitter.im/geopython/GeoHealthCheck?at=5ad5be0a5f188ccc1572cd90) and has established that the check succeeds with OpenSSL 1.0.2g 1 Mar 2016 (eg Ubuntu 16.04) and fails with OpenSSL 1.0.1f 6 Jan 2014 (eg Ubuntu 14.04)

**Comment by justb4** [comment]
@archaeogeek Can we close this one? There is really not a lot we can do. The new https://demo.geohealthcheck.org (Docker Alpine Linux) shows that with uptodate SSL libs connection problems are quickly solved.

**Comment by archaeogeek** [comment]
Sure
