### ISSUE TITLE
Problem with email notification

### ISSUE THREAD

**Issue by Gabriel-Desharnais** [geopython/GeoHealthCheck#206]
So, I created a resource, add a probe that should failed and run the tests:

The test result behave as it should in the GUI
![screenshot_20180601_134519](https://user-images.githubusercontent.com/17755977/40855381-6e0a7b38-65a2-11e8-9fbe-b3a7751bd666.png)

but I received no email and I'm pretty sure that I configured it properly

the output of the test run is
```
init.py: created GHC App instance
START - Running health check tests on 2018-06-01T17:43:49.330397
Testing FTP http://perdu.com
Adding Run: success=False, response_time=0.96714s

Notifying: status changed: result=Still Failing
No handlers could be found for logger "notifications"
END - Running health check tests on 2018-06-01T17:43:49.931270
```

If I add the following lines to the `notifications.py` file at line 268:
``` python
import traceback, sys
print traceback.print_exc(file=sys.stdout)
```
I get the following output:
```
init.py: created GHC App instance
START - Running health check tests on 2018-06-01T17:54:41.740688
Testing FTP http://perdu.com
Adding Run: success=False, response_time=0.96078s

Notifying: status changed: result=Still Failing
Traceback (most recent call last):
  File "/home/gabriel/Programmation/GeoHealthCheck2/GeoHealthCheck/GeoHealthCheck/notifications.py", line 266, in notify
    chann_handler(config, resource, run, status_changed, result)
  File "/home/gabriel/Programmation/GeoHealthCheck2/GeoHealthCheck/GeoHealthCheck/notifications.py", line 78, in do_email
    msg = MIMEText(msgbody)
  File "/usr/lib/python2.7/email/mime/text.py", line 30, in __init__
    self.set_payload(_text, _charset)
  File "/usr/lib/python2.7/email/message.py", line 226, in set_payload
    self.set_charset(charset)
  File "/usr/lib/python2.7/email/message.py", line 262, in set_charset
    self._payload = self._payload.encode(charset.output_charset)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 65: ordinal not in range(128)
None
No handlers could be found for logger "notifications"
END - Running health check tests on 2018-06-01T17:54:42.303178
```
Which seems to me like a **utf-8** type of problem. I made the following modification at line 78 in `notifications.py`:
from:
``` python
msg = MIMEText(msgbody)
```
to
``` python
msg = MIMEText(msgbody,'plain','utf-8')
```
After this modification I get the following output when running the tests:
```
init.py: created GHC App instance
START - Running health check tests on 2018-06-01T18:02:17.747627
Testing FTP http://perdu.com
Adding Run: success=False, response_time=0.89622s

Notifying: status changed: result=Still Failing
END - Running health check tests on 2018-06-01T18:02:28.403460
```
And if I look in my email account:
![screenshot_20180601_141527](https://user-images.githubusercontent.com/17755977/40856683-b6e901fe-65a6-11e8-9e55-d7fcf858e64d.png)

So this modification can solve by problem
My version of GHC **0.4-dev** and I'm using python **2.7.12**

A description of the proposed modification:
class email.mime.text.MIMEText(_text[, _subtype[, _charset]])
subtype = "plain"                           : the email will have a content type of `text/plain`
_charset="utf-8"
ref:
[https://docs.python.org/2/library/email.mime.html#email.mime.text.MIMEText](https://docs.python.org/2/library/email.mime.html#email.mime.text.MIMEText)

I shall create a pull request for this issue

**Comment by tomkralidis** [comment]
+1 to @justb4's recommendation.

**Comment by Gabriel-Desharnais** [comment]
Since #207 have been merged this issue can be closed
