### ISSUE TITLE
Add setup for Apache or service deploymemt

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#21]
## User Story
As a GeoHealthCheck (GHC) administrator
I want to run GHC as a service
So that I can manage the application as a 

## Options
1. Setup as a system service (eg $ sudo service geohealthcheck start|stop|restart)
1. Trigger something in Apache config to tie in GHC

Any ideas?

**Comment by tomkralidis** [comment]
@samperd added to master.  Running `paver create_wsgi` will create the `GeoHealthCheck.wsgi` wrapper and Apache `GeoHealthCheck.conf` configuration which you can `Include` in an Apache setup.  Can you try this out and let me know if this works for you?

**Comment by hannesaddec** [comment]
Added WSGI on a windows with XAMPP and works fine.
