### ISSUE TITLE
Configurable geocoder

### ISSUE THREAD

**Issue by cezio** [geopython/GeoHealthCheck#210]
At the moment GHC is using freegeoip.net service to translate ip to location. This is 3rd party service, and can return errors unexpectedly. GHC could have pluggable geocoder backends, so other options (local copy of GeoIP from MaxMind for example) could be used too.

**Comment by justb4** [comment]
Makes sense. As each GeoIP provider will have its own custom protocol/format, a pluggable geocoder could be applied. The GHC Plugin system is very generic, based on [Plugin](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugin.py) base class, not just for `Probes` and `Tests`. As also notifications could be Plugins, a Plugin-based GeoIP provider is possible, easier, as no specific GUI is required.

**Comment by justb4** [comment]
Pasting comment from #216:

Via #216 GHC uses [IP-API](http://ip-api.com/json/) for now, so geocoding is working.

It would not bee too hard to use our `Plugin` system with  `IP-API` as the default `Plugin`. Other providers can then be configured at will. Most will just need a `url`, `key` and return `latitude`, `longitude` in JSON, so all those could use a single `Plugin` class. Within the `config_site.py`, we just configure and parameterize the `Plugin`:

```
GEOIP = {
  'plugin': 'GeoHealthCheck.plugins.geoip.generic',
  'parameters': {
    'url_template': 'https://mygeoipprovider.com/?key=<mykey>&ip=%s&format=json',
    'lat_field': 'latitude',
    'lon_field': 'longitude'
  }
}

# default IP-API in config_main.py

GEOIP = {
  'plugin': 'GeoHealthCheck.plugins.geoip.generic',
  'parameters': {
    'url_template': 'http://ip-api.com/json/%s',
    'lat_field': 'lat',
    'lon_field': 'lon'
  }
}

# Create at runtime
geoip_provider = Factory.create_obj(CONFIG['GEOIP']['plugin'])
geoip_provider.init(CONFIG['GEOIP']['parameters'])
lat, lon = geoip_provider.lookup(ip)
# etc
```

This will cover most of the Geo-IP providers I've seen, or APIs on self-hosted Geo-IP Databases, or maybe even a local DB lookup,  as @cezio suggests in #210. Our Plugin system can instantiate and parameterize the Plugin. Possibly this could be an array of geocoders, if one fails.
