### ISSUE TITLE
user password is stored in plain text in the database

### ISSUE THREAD

**Issue by archaeogeek** [geopython/GeoHealthCheck#218]
In the user table in the database the password for all users including admins is stored in plain text, as an enhancement can this be encrypted?

**Comment by justb4** [comment]
working on this one, good progress, including smart DB upgrade. Remaining challenge dealing with lost passwords: the current method needs revision. After the upgrade GHC has no way to decrypt passwords, which is a good thing. Common is to send a temp-link for a password reset. Some administration is needed for that.

**Comment by justb4** [comment]
AFAICS this issue is solved, runs at demo site as well. Be sure to backup db and run `paver upgrade` first. See also docs upcoming 0.6.0: http://docs.geohealthcheck.org/en/latest/install.html#upgrade-notes-v0-6-0 @archaeogeek can you close if ok?

**Comment by archaeogeek** [comment]
Upgrade went very smoothly, and password encryption seems to be working. I'll close this, but I also have to check the "forgot password" functionality- I'll submit a separate issue if needed. Thanks!
