### ISSUE TITLE
Add time scale selector to line chart

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#22]
## User Story

As a GeoHealthChecker (GHC) user
I want to select a time scale for historical tests of each resource
So that I can "zoom in"  "zoom out" on the time scale to further investigate patterns and trends
## Details
- Given a GHC instance such as http://geohealthcheck.osgeo.org/, I want to select a resource, such as http://geohealthcheck.osgeo.org/resource/1 and then choose a time scale to visualize the data.
- Start and end dates COULD be selected by two calendar widgets or controlled text entry boxes
- A slider could used where you can slide a start date and end date picker. The slider would display the start and end dates of all possible records.
- the scale (y-axis) of the chart should also change according to the response time of the selected time range, which may differ from the WHOLE timeline.
## Discussion
- Even with a 30 day horizon, those dots get pretty close together and are hard to visualize
- I like using GHC to also look at response times. As such, if there was a slow response time of a couple of seconds previously in the history it greatly affects the rest of the scale. So I would like to visualize patterns and trends relative to tests within the selected timescale.

**Comment by justb4** [comment]
I think this has been resolved in v0.6.0 via issue #229 and related PR #230 . This introduced visualizing Run history using `Plotly.js` graphs. See e.g. https://demo.geohealthcheck.org/resource/64?lang=en. So I close, please reopen if still required.
