### ISSUE TITLE
add support for monitoring WFS3

### ISSUE THREAD

**Issue by tomkralidis** [geopython/GeoHealthCheck#221]
The [WFS 3](https://github.com/opengeospatial/WFS_FES) standard is a clean break from previous OGC interface specifications.  Add support for monitoring WFS 3 (starting point is a WFS 3 parser in OWSLib).

**Comment by justb4** [comment]
+1. Interesting question is if we need to make a separate Resource Type for WFS3 (I think so), as it breaks from the traditional `OWS GetCapabilities` pattern, like WFS v1 and v2 as WFS3 uses REST-style. For one thing the generic OWS Capabilities Probe cannot be used.  

In that sense WFS3 is more similar to SensorThings API (STA), and its main Probe: https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugins/probe/sta.py

**Comment by tomkralidis** [comment]
Maybe we need a base 'OWS Rest' class, since WFS3 and many things coming after it will follow the same pattern.

**Comment by justb4** [comment]
Ok, need to figure out useful Probes for WFS3. Hoping indeed for more OWS REST...

**Comment by justb4** [comment]
Think indeed we can have a base Probe for `OGC API`. The related standards (Features, Maps etc) follow that pattern. Even more advanced to feed it an OpenAPI YML, do all semantic Checks based on schema, but that would be quite a project by itself, probably already existing somewhere for OpenAPI. 

Like said the easiest approach is something similar like:
https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugins/probe/sta.py all Checks there can be re-used. A basic "Capabilities"-like Probe and possibly a "crawler" that would fetch Items(-counts) for each Collections.

Think this will be a nice promotion and hopefully usage of GHC for the OGC APIs.

**Comment by justb4** [comment]
Yes, using OWSLib for the [WFSDrilldown Probe](https://github.com/geopython/GeoHealthCheck/blob/issue-221-wfs3/GeoHealthCheck/plugins/probe/wfs3.py). Needed to upgrade requirements.txt to 0.17.1 to use WFS3 client, hope this is further a minor upgrade (no lxml issues e.g.).

**Comment by justb4** [comment]
`WFS3Drilldown Probe` working see:

https://demo.geohealthcheck.org/resources?lang=en&resource_type=OGC%3AWFS3

Maybe keep open and add an OGC API (OpenAPI) validation Probe based on https://github.com/p1c2u/openapi-spec-validator ? Will be quite trivial to implement.

**Comment by justb4** [comment]
Think we can close for now? We have basic support with two new Probes. A third Probe could be a WFS3GetItem Probe (similar to [WMS GetMap Probe](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugins/probe/wms.py#L6) i.e. one could select a Collection from metadata, fill in id, bbox an whatever needed) in  new specific issue ok?

**Comment by justb4** [comment]
Works ok on master, closing to proceed with v0.6.0 release, pls reopen if still needed.
