### ISSUE TITLE
create project logo

### ISSUE THREAD

**Issue by tomkralidis** [geopython/GeoHealthCheck#225]
I think this has been discussed in the past, but it's high time to add a project logo.  Proposals/ideas welcome!

**Comment by hannesaddec** [comment]
See attached proposal..

**Comment by tomkralidis** [comment]
Thanks @hannesaddec. I do not see the attachment?

**Comment by mirzazulfan** [comment]
Hi @tomkralidis , What about this?
![ghc](https://user-images.githubusercontent.com/36124339/49145305-0dc92300-f332-11e8-8f7a-d6b20554694b.png)

**Comment by justb4** [comment]
Proposal:

![image](https://user-images.githubusercontent.com/582630/64062149-e8808280-cbeb-11e9-846b-c636bba1c99d.png)

Text: `RobotoSlab`
Colors: Blue: Lapis Lazuli (#306998) (Python Logo Dark Blue) , Red: #910606

**Comment by tomkralidis** [comment]
+1

**Comment by justb4** [comment]
ok fast forward, logos can be found here online:
https://github.com/geopython/GeoHealthCheck/tree/gh-pages/logo

this is how new webpage should look (black background did not play nice with transparent logo).

![image](https://user-images.githubusercontent.com/582630/64063715-a9106100-cc00-11e9-8862-d480a6a4edf4.png)

**Comment by justb4** [comment]
Think we're done right?

**Comment by tomkralidis** [comment]
Thanks @justb4 !
