### ISSUE TITLE
fix https setup

### ISSUE THREAD

**Issue by tomkralidis** [geopython/GeoHealthCheck#226]
Going to https://docs.geohealthcheck.org/ results in problems with the HTTP setup:

```
docs.geohealthcheck.org uses an invalid security certificate.
The certificate is only valid for the following names: *.readthedocs.io, readthedocs.io
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```
Not sure if this is a DNS issue?

**Comment by justb4** [comment]
SSL support was for custom domains was recently added to ReadTheDocs where our documentation is hosted. I just made the DNS-changes at our domain-provider plus Admin settings in RTD. as outlined [here](https://docs.readthedocs.io/en/latest/custom_domains.html#custom-domain-ssl):

* docs.geohealthcheck.org changed CNAME to readthedocs.io
* re-edit primary domain in RTD Admin, status is now `HTTPS status: pending_validation`

Will take some time. Will revisit if staying forever in`HTTPS status: pending_validation`.

**Comment by tomkralidis** [comment]
Works! Thanks.

**Comment by justb4** [comment]
Yeah, took a long time, then removed and re-added domain in RTD and worked in a minute!

**Comment by justb4** [comment]
Only redirect from http --> https is not yet in place:
https://github.com/rtfd/readthedocs.org/issues/2652#issuecomment-413268346
but ok.
