### ISSUE TITLE
Search Existing Web Resources

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#23]
## User Story
As a user
I want to search existing web resources using keywords and URL's
So that I can quickly find the resource amongst a large list of resources

## Details
* a simple search box to search multiple fields
  * search title
  * search owner
  * search URL
* perhaps ability to filter results
  * filter on owner
  * filter on owner by resource type 
* perhaps leverage google syntax such as "site:gc.ca" that will return all resource URL's containing the given domain or "url:getCapabilities" to return all URL's with a given pattern in the URL
* Search box should be open search enabled (http://www.opensearch.org/Home) so you can search from the browser search.

## Discussion
* As the list of tracked resources grow (eg 50+) I find that I use ctrl-f a lot. however this does not search the actual URL
* Having a simple search mechanism would be good.
* perhaps usage of various filters beyond resource type could also help.

**Comment by tomkralidis** [comment]
@samperd implemented in a86adb99b6450029e7c0ef7273b01a2a1e081a3e. Can you verify and close if this works for you?

**Comment by samperd** [comment]
First iteration looks good.

How much effort to add an open search description document?

http://www.opensearch.org/Specifications/OpenSearch/1.1#OpenSearch_description_document

**Comment by tomkralidis** [comment]
@samperd the first iteration provided a simple web-based filter.

The codebase now supports a simple search syntax with the following rules:

- `q=` searches on title field (may seem duplicative for now)
- `q=title:foo` searches on title field
- `q=url:foo` searches on url field
- `q=site:.org` searches on domain of url in url field
- `q=owner:foo` searches on the owner username field

Note that resource type is already realized by the `resource_type` query parameter.

 and OpenSearch support.  Let me know if this works for you.  Note it would be great to have this added to the docs.

**Comment by samperd** [comment]
OpenSearch works great. Woot Wooot!!!!

The searches work fine through the URL too.

however, when I try "title:foo" inside the search text box it does not return any results.

**Comment by tomkralidis** [comment]
@samperd UI-based search now implemented in master.  Can you verify?

**Comment by tomkralidis** [comment]
Closing.  Feel free to reopen if there are bugs/etc.
