### ISSUE TITLE
Average Response time of each resource and compare all resources

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#24]
## User Story
As a user of GeoHealthCheck (GHC)
I want to see both the last response time and average response time of all resources on the main dashboard
So that I can compare the most recent test response to the average response time

## Details
* Given a dashboard such as http://geohealthcheck.osgeo.org/
* provide an extra column that provides the average response time
* maybe also a column for "Fastest" and "slowest" response times.
* perhaps these other columns could also be added to each resource as well. They seem like decent stats to have listed.

## Discussion
* Having started tracking many sites i find that the last response times listed in the main dash may not provide a comparative snapshot of site performances.
* I have found that the only way to see if sites are trending for a response rate is by clicking all resource one by one.
* right now to figure out the mean, min, max, mode is to export the data in CSV (great feature BTW) and do the math in a spreadsheet. THis is ok for 5 sites. right now I am pushing 50+ so this is time consuming. Yes it could be scripted, however I think it is a worthwhile feature to add in the app itself.

**Comment by tomkralidis** [comment]
@samperd implemented in eeff9fe034d7eba6a685cdd28ed226c3c9369778.  Can you verify and close if this works for you?

**Comment by samperd** [comment]
Good stuff. Closed
