### ISSUE TITLE
change default WMS version to 1.3.0

### ISSUE THREAD

**Issue by tomkralidis** [geopython/GeoHealthCheck#248]
Looks like we support both 1.1.1 and 1.3.0 with 1.1.1 being the [default](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugins/probe/owsgetcaps.py#L62). We should update so that 1.3.0 is tested first given it is more recent, and while organizations support both 1.1.1, we should let version negotiation take care of trying 1.3.0 first and then 1.1.1.

**Comment by justb4** [comment]
Like to focus on bringing out 0.7.0, create maintenance branch and then do Py2-->Py3 upgrade targeted for v0.8.0, so moving versions for outstanding 0.7.0 issues.

**Comment by borrob** [comment]
I made a PR (#307) to change the default. Is it this easy, or am I missing something?

**Comment by justb4** [comment]
Ok, the other place where WMS-versions are used is when adding a WMS `Resource `in [healthcheck.sniff_test_resource()](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/healthcheck.py#L149). Here already `1.3.0` is tested first, then `1.1.1`. `sniff_test_resource` is there historically, unrelated to `Probes` and mainly to get a `<title>` for the `Resource.title`. But even if this test fails the `Resource` is still added. I think we are fine with PR #307 and can close this issue.
