### ISSUE TITLE
Flask-Login dependency issue on CentOS 7

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#26]
failures with Flask-Login 0.3.0, but works with 0.2.11

One a new CentOS 7 system I tried installing GHC.

There were various deps that were required (eg develop RPM package), paver through some errors along the way (complaining about gcc).

Then once i tried to srtat the app the service ran but we were getting errors due to the templates.

A temp fix was in line 48 of the layout.html file we remove the enclosed brackets.

The long term fix was to:

pip uninstall Flask-Login
pip install Flask-Login==0.2.11

Cheers

**Comment by tomkralidis** [comment]
@samperd thanks for the report.  This is rooted in the following [change](https://github.com/maxcountryman/flask-login/blob/master/CHANGES#L25) Flask-Login 0.3.0.

I've pegged the Flask-Login dependency e84125edbb97b3b8e2e91df2f211ad844e7dabc3 to 0.2.11 until packaging catches up on major distributions.
