### ISSUE TITLE
Proposal: drop de_DE translations

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#268]
This has been discussed, probably proposed before (think by @astroidex ?): GHC already has a ["de" (*"German"* in Language menu) translation](https://github.com/geopython/GeoHealthCheck/tree/master/GeoHealthCheck/translations/de/LC_MESSAGES), which is updated regularly. But there is also a ["de_DE",  (*"German (Germany)"* in Language menu) ](https://github.com/geopython/GeoHealthCheck/tree/master/GeoHealthCheck/translations/de_DE/LC_MESSAGES) not updated regularly. 

My proposal is to drop "de_DE" and only maintain "de".

**Comment by astroidex** [comment]
Hello @justb4. Thanks for bringing the topic back again. Yes we discussed about it some month ago.

+1 to drop "de_DE" and keep "de"

**Comment by justb4** [comment]
Ok, done via PR #270, see also Language menu on https://demo.geohealthcheck.org/
