### ISSUE TITLE
Docker's Database creation doesn`t have into account the variable DB_NAME

### ISSUE THREAD

**Issue by dersteppenwolf** [geopython/GeoHealthCheck#271]
Docker's Database creation doesn`t have into account the variable DB_NAME
See:
https://github.com/geopython/GeoHealthCheck/blob/1cc4b3efc56a154044adecf1f8b33962fe673efe/docker/scripts/configure.sh#L45

Doesn´t work if the database doesn´t have the same name as the user

**Comment by justb4** [comment]
@dersteppenwolf Can you expand your setup? The database (PostgreSQL) should run within another Docker Postgres container (where the DB is created).  The [line above](https://github.com/geopython/GeoHealthCheck/blob/1cc4b3efc56a154044adecf1f8b33962fe673efe/docker/scripts/configure.sh#L45) merely tests if the DB host/service is available, trying to list all the DB's within the PG server (`\l` command), hence `${DB_NAME}` is not required.

But does it work for you if you add `${DBNAME}` ? Like

`until psql -h "${DB_HOST}" -U "${DB_USER}" -c '\l' ${DBNAME}; do`

**Comment by dersteppenwolf** [comment]
> `until psql -h "${DB_HOST}" -U "${DB_USER}" -c '\l' ${DBNAME}; do`
Surely in that way it works.  
The user I´m using has limited privileges, so that could be the problem.

best.

**Comment by justb4** [comment]
Think `pg_isready` is a better option: https://www.postgresql.org/docs/10/app-pg-isready.html
Will try that.

**Comment by justb4** [comment]
`pg_isready` works and is in `latest` GHC Docker version.
