### ISSUE TITLE
expose language switcher to app.py

### ISSUE THREAD

**Issue by hannesaddec** [geopython/GeoHealthCheck#28]

**Comment by tomkralidis** [comment]
@hannesaddec add in master (see top right Language drop down).  Can you please verify?

**Comment by hannesaddec** [comment]
Confirm that the layer switcher is there, however i receive an undefined error: 'lang' is undefined now.

**Comment by tomkralidis** [comment]
Thanks for the report.  Fixed in master.

**Comment by hannesaddec** [comment]
Works for me :8ball:
