### ISSUE TITLE
WFS3 Probe: change name to id for collection identifier

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#283]
## Problem
Recently and according to specs a `Collection` within OGC API - Features has an `id` attribute. Several implementations like [pygeoapi](https://pygeoapi.io) were using `name`. A recent change from `name` to `id` in `pygeoapi` makes the `pygeoapi` [WFS3 Drilldown Probe](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugins/probe/wfs3.py#L9) fail. 

## Solution
The WFS3 Drilldown Probe needs to change `name` to `id` when testing a Collection, like on [this line](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugins/probe/wfs3.py#L87) and [this line](https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/plugins/probe/wfs3.py#L94).

**Comment by pvgenuchten** [comment]
can you set use of "name" as a warning for upcoming months? And at some point in future make it an actual error.

**Comment by justb4** [comment]
@pvgenuchten bit hard to realize: each `Check` renders `True` or `False`. And hard to determine when to switch, also with several versions deployed at some point. One can always set `Basic` (i.s.o. `Full` mode for the `WFS3Drilldown`  Probe so it won't crawl into all Collections. And `pygeoapi` is compliant now..

**Comment by justb4** [comment]
Fixed via PR #284
