### ISSUE TITLE
Error - Could not derive coordinates: 'lat'

### ISSUE THREAD

**Issue by dersteppenwolf** [geopython/GeoHealthCheck#289]
The following error appears frequently on web:

`2019-10-05 12:55:18,719 - GeoHealthCheck.util - ERROR - Could not derive coordinates: 'lat'
Traceback (most recent call last):
  File "/GeoHealthCheck/GeoHealthCheck/util.py", line 200, in geocode
    lat, lon = content['lat'], content['lon']
KeyError: 'lat'
`

Enviroment: Docker
Bd: Postgresql

**Comment by justb4** [comment]
This happens on Add, Edit-Save for a `Resource`, when GHC tries to derive the lat, lon coordinates from the Resource URL via http://ip-api.com/json/. Either the coordinates cannot be found or in some cases http://ip-api.com/json/ does not allow. In both cases this error is non-fatal and will not influence any GHC functioning. But maybe better to make this a Warning or Info message.

**Comment by dersteppenwolf** [comment]
> But maybe better to make this a Warning or Info message.

Sounds Ok.  Some of the services that we are monitoring are only available on our LAN.
