### ISSUE TITLE
Ability to add same Service using same URL multiple times

### ISSUE THREAD

**Issue by BenGunnewijk** [geopython/GeoHealthCheck#292]
**Is your feature request related to a problem? Please describe.**
When I quickly want to test different settings for a service, without throwing away the current test settings, I would like to be able to add a copy of the service checking that URL to alter its settings. However when I try to do this I get an error telling me that there is already a service using that URL.
"Service already registered (ESRI:FS, https://services5.arcgis.com/etc/etc/FeatureServer)"

This feature would mostly be useful for debugging whether a service is added with the correct settings.

**Describe the solution you'd like**
Instead of an error popping up when adding a service with an URL that already exists I would like this to not appear or instead just be a warning.

**Describe alternatives you've considered**
Using multiple accounts would allow testing new settings but this would be a hassle with logging in and out just for tests.
Business as usual solution where I keep changing the service that is already there would work but doesn't have my preference.

**Comment by justb4** [comment]
Good suggestion. Another use case is to apply different schedules on a Resources with same URL: e.g. once a day full-testing, every 20 mins minimal "uptime" test.

**Comment by justb4** [comment]
Ok works!
