### ISSUE TITLE
Capability to update Resource Names

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/GeoHealthCheck#295]
**Is your feature request related to a problem? Please describe.**

I might be wrong, but I think a Resource Name is determined when the Resource is added to GeoHealthCheck (GHC). The problem is a Resource Name may change over time (e.g. in the corresponding WMS xml tag) but GHC still uses the initial Name. 

**Describe the solution you'd like**

A way to manually or automatically update the Resource Name in GHC.

**Describe alternatives you've considered**

Manually editing the database (if that's where it's stored) is an option, but better if GHC can handle this feature cleanly.

**Comment by justb4** [comment]
The `Resource Name` is automatically determined during the initial *Add* operation. The Resource is "sniffed" using a default Resource-Type-dependent HTTP Request: e.g. a `GetCapabilities` (`title` element)  for an `OWS` Resource. This is a "best-effort": depending on the Resource Type: e.g. Name is extracted from `<title>` element for a URL Resource. This may fail for many reasons, in those cases `Unnamed` is substituted as initial name (which can be changed, see next).

The Resource Name can always be manually changed within the *Edit* window, see screenshot below (and don't forget pressing `Save` button at bottom):

![image](https://user-images.githubusercontent.com/582630/67372347-0a5c0d00-f57e-11e9-9c0d-12db32a74790.png)

@alexandreleroux I don't see an issue here or am I missing something? Maybe in an early GHC version this was not possible?

**Comment by alexandreleroux** [comment]
@justb4 big thanks for the detailed feedback. I confirm, Admins can indeed edit the resource's name. So it can easily be updated by admins.

I'll close this feature request (sorry for the noise!), but still think that maybe in the future, having Resource names automatically be updated from, for WMS, the corresponding GetCapabilities, would be useful for those whom have Resource names that change over time (which is our case).

Big thanks @justb4 :-)
