### ISSUE TITLE
Settings display to be translated

### ISSUE THREAD

**Issue by hannesaddec** [geopython/GeoHealthCheck#30]
The settings are partly translated (e.g. History and Days) however the testing frequency is not translated (e.g. 'hourly','daily','weekly','monthly','yearly'). Should we translate it as well.
Should we store in the DB in a settings table ? or to complex ? 
Suggestion: drive the cron jobs from that setting in the DB as well?

**Comment by justb4** [comment]
As cron jobs have been phased out for per-Resource scheduling I close this issue. Pls re-open if otherwise.
