### ISSUE TITLE
Serve local help files

### ISSUE THREAD

**Issue by hannesaddec** [geopython/GeoHealthCheck#31]
Currently help files are served from github.com/geopython/GeoHealthCheck.
To avoid unnecessary traffic, the docs output could be statically served via Flask from local repository

**Comment by tomkralidis** [comment]
@hannesaddec implemented in e9fedc43aa7cd6498b13354b18a87542ac05546f.  When running `paver setup` now calls `refresh_docs` (which you can call independently via `paver refresh_docs`), which will additionally copy the docs to `GeoHealthCheck/static/docs`, and is now the default help link in the UI.  Can you verify?

**Comment by hannesaddec** [comment]
@tomkralidis works for me
