### ISSUE TITLE
wms with basic authentication does not work

### ISSUE THREAD

**Issue by deRightDirection** [geopython/GeoHealthCheck#323]
I configured a wms-service with basic authentication.
GHC seems to have issues with this wms-service:

Probe | WMS GetCapabilities
-- | --
False
0.143071
Checks                                                                CheckHTTP status should not be errored                                                       SuccessFalse                                                       MessageHTTP Error status=404                                                                                              CheckValid XML response                                                       SuccessFalse                                                       Message(<class  'lxml.etree.XMLSyntaxError'>, XMLSyntaxError('Opening and ending tag  mismatch: hr line 1 and body, line 1, column 986'), <traceback object  at 0x7f9a7a2e0140>)                                                                                              CheckResponse NOT contains OWS Exception                                                       SuccessTrue                                                       MessageOK                                                                                              CheckResponse contains strings                                                       SuccessFalse                                                       MessageTitle> not in response text | HTTP status should not be errored | False | HTTP Error status=404 | Valid XML response | False | (<class  'lxml.etree.XMLSyntaxError'>, XMLSyntaxError('Opening and ending tag  mismatch: hr line 1 and body, line 1, column 986'), <traceback object  at 0x7f9a7a2e0140>) | Response NOT contains OWS Exception | True | OK | Response contains strings | False | Title> not in response text
HTTP status should not be errored
False
HTTP Error status=404
Valid XML response
False
(<class  'lxml.etree.XMLSyntaxError'>, XMLSyntaxError('Opening and ending tag  mismatch: hr line 1 and body, line 1, column 986'), <traceback object  at 0x7f9a7a2e0140>)
Response NOT contains OWS Exception
True
OK
Response contains strings
False
Title> not in response text

How could we solve this?

**Comment by justb4** [comment]
Error 404 is `File not Found`.  What URL did you enter. Remember to not include the GetCapabilities query string.

**Comment by justb4** [comment]
No response from @deRightDirection . Closing now. Please re-open if still an issue.
