### ISSUE TITLE
Reset Admin password

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#33]
As a Geo health Check administrator
I want to be able to reset the admin password
So that I can reset the account in the event that the password was forgotten

**Comment by samperd** [comment]
This could be achieved through a couple of different ways:
* Have a process run at the command line (paver?)
* Send an e-mail to the admin address already in the DB.
* Ask security challenge questions.
* provide a public/private key check when you register. like how SSH handles it.

**Comment by tomkralidis** [comment]
Impemented in e34bc17a5d27f52b7f196872402135b09c602931
