### ISSUE TITLE
Comma saving issue for Notify e-mails

### ISSUE THREAD

**Issue by BenGunnewijk** [geopython/GeoHealthCheck#346]
**Bug description**
We use several services of type ESRI ArcGIS FeatureServer (FS) which have a setting for Notify emails. A comma separated list of e-mail addresses. However since recently such a service cannot be saved with white space between the commas and e-mail addresses. However the service automatically adds one space after each comma when it is saved. 

**To Reproduce**
1. Add a ESRI ArcGIS FeatureServer (FS) service (might happen on other services too?)
2. Save the service with multiple comma separated notify email addresses
3. Open the service again for editing
4. The service has added spaces behind the comma's and cannot be saved before they are removed.

**Expected Behavior**
The service can be saved even when there is whitespace after a comma.

**Context**
 - GeoHealthCheck Version - 0.8.3

**Comment by justb4** [comment]
Ok, thanks for this. Will apply to other Resource types as well I think, as the email notification field is generic for all Resource types. Looks like  simple "strip-whitespace" fix.

**Comment by borrob** [comment]
Fixed by PR #350

**Comment by justb4** [comment]
@BenGunnewijk : issue should be fixed. You can test/verify on demo.geohealthcheck.org. Fix/PR #350 will be included in the next GHC version which will then appear in geoqos.com.
