### ISSUE TITLE
TMS automated test fail

### ISSUE THREAD

**Issue by borrob** [geopython/GeoHealthCheck#348]
**Describe the bug**
There are automated tests to check a new build of GeoHealthCheck. To test the TMS probes, it uses the Dutch PDOK register. Per March 1 2021 they phased out TMS [ref: [news article in Dutch](https://www.pdok.nl/-/pdok-gaat-tms-uitfaseren)]

**To Reproduce**
Steps to reproduce the behavior, e.g.:

Run `paver run_tests` or check the [job log of the latest Travis build](https://travis-ci.org/github/geopython/GeoHealthCheck)

**Expected Behavior**
The test should pass.

**Screenshots or Logfiles**
See the [job log of the latest Travis build](https://travis-ci.org/github/geopython/GeoHealthCheck)

**Context (please complete the following information):**
 GHC version 0.8.3 (but most likely that all versions are affected).

**Additional context**
The TMS resource is configured here: https://github.com/geopython/GeoHealthCheck/blob/506a4bd3c1508ffffd5f48099430941d0ce56afb/tests/data/resources.json#L88

**Possible solution**
Are there any other publicly available TMS hosts we can use instead?

**Comment by justb4** [comment]
Thanks. Yes, was aware of the PDOK changes, so many other places to make changes, forgot GHC.
We may use OpenBasisKaart from OpenGeoGroep:
https://www.openbasiskaart.nl/mapcache/tms/1.0.0/

**Comment by borrob** [comment]
For the sake of completeness: also fixing the failing WFS3 test in the attached PR (#349)

**Comment by borrob** [comment]
This issue is fixed with PR #349.
Closing ticket.
