### ISSUE TITLE
If config.py for self registration is set to false - show proper error page

### ISSUE THREAD

**Issue by hannesaddec** [geopython/GeoHealthCheck#35]

**Comment by tomkralidis** [comment]
@hannesaddec proposed workflow for login page:

if self registration is set to false, then show notice on Login page **without** displaying the `Register` link.

Would this work?

**Comment by tomkralidis** [comment]
@hannesaddec implemented in master.  Can you verify/validate?

**Comment by hannesaddec** [comment]
Validated on 130389a
