### ISSUE TITLE
Responsive layout issue: content inaccessible for certain widths

### ISSUE THREAD

**Issue by alexandreleroux** [geopython/GeoHealthCheck#36]
Issue with GeoHealthCheck's reponsive layout: content can become hidden / inaccessible. See attached screenshot.

The problem: GeoHealthCheck content is hidden at certain browser window width. Because there's no horizontal scrollbar, the content is indeed inaccessible to users for those window widths.

Steps to reproduce: go to http://geohealthcheck.osgeo.org/ or another GHC installation, and resize the window until content becomes inaccessible.

![geohealthcheck-responsive-issue](https://cloud.githubusercontent.com/assets/874004/13989454/5f7ccb72-f108-11e5-9f0d-5cfd9ea9398b.jpg)

**Comment by kngai** [comment]
This is due to the `.sidebar` CSS properties in `sb-admin-2.css (line 131)` setting a static width to 250px, which conflicts with the bootstrap `col-*` classes. If that CSS can't be removed, one minor fix is adding this CSS override:
`.col-md-2.sidebar { width: 16.6667% !important; }`

**Comment by tomkralidis** [comment]
@alexandreleroux fixed in 30af45ba502c42c7777112edf68ac2be684815f1.  Can  you validate/close if this works for you?

**Comment by alexandreleroux** [comment]
Works, closing. Thanks! -- Alex
