### ISSUE TITLE
New probe for WMTS

### ISSUE THREAD

**Issue by fsteggink** [geopython/GeoHealthCheck#379]
I'd like to see a new probe for WMTS requests, in order to check GetTile requests. And of course also a REST variant. Currently it is missing from GHC, while WMS and WFS have more specific probes

**Comment by justb4** [comment]
Ok, good, have you been able to look at: https://github.com/geopython/GeoHealthCheck/issues/420 ?

**Comment by fsteggink** [comment]
As far as our use case is concerned, the WMTS probe is working well. IMO it goes beyond our responsibility to have it working properly for all kinds of WMTS services (and software implementations) out in the wild. If other persons are interested in having the WMTS probe working well for those services, they're free to submit PRs.
