### ISSUE TITLE
Allow adding new user by a script or paver create flags

### ISSUE THREAD

**Issue by yjacolin** [geopython/GeoHealthCheck#38]
I am working to a Docker images for GeoHealthCheck and I need a way to create the admin user (login, password, email) in a non interactive way.

**Comment by tomkralidis** [comment]
@yjacolin implemented.  Run `paver create -u foo -p bar`.  Does this work for you?

It would be great if the Docker images could be part of GeoHealthCheck codebase -- great to hear this!

**Comment by yjacolin** [comment]
email is missing :)

(Note that I have almost the same issue with the secret key)

**Comment by tomkralidis** [comment]
@yjacolin added support for email.  Note that for the secret key, paver merely provides a suggestion.  In a Docker context you can simply set your own (perhaps not so secret) key to complete the install.

**Comment by yjacolin** [comment]
Thanks, I am working back to the Dockerfile, PR before this summer ;)
