### ISSUE TITLE
What is the recommended way to translate?

### ISSUE THREAD

**Issue by severo** [geopython/GeoHealthCheck#42]
Hi,

I understand you are using Babel [1] to manage i18n in the project. What is the recommended way to translate? Just creating new files for new languages, and editing these files, o is there a recommended web or GUI interface for this?

[1] http://babel.pocoo.org/en/latest/index.html

**Comment by tomkralidis** [comment]
Hi @severo thanks for the report.  We used to use Transifex but we found it easier for forking and implementing within the repository.  Simply fork the project, add your language in https://github.com/geopython/GeoHealthCheck/tree/master/GeoHealthCheck/translations and submit a pull request.  I'm cc'ing @hannesaddec who contributes to GeoHealthCheck for his thoughts.

**Comment by severo** [comment]
OK, perfect. We will contribute with Spanish and French translations in the following days or weeks.

**Comment by tomkralidis** [comment]
That's awesome!  Looking forward to this and thanks!

**Comment by hannesaddec** [comment]
I will look around for some more languages... Portuguese Russian Chinese or Arabic.

Mit TouchDown von meinem Android-Telefon gesendet (www.symantec.com)

-----Original Message-----

**Comment by tomkralidis** [comment]
@hannesaddec do you use any specific tools for translating GeoHealthCheck or directly in the .po files?

**Comment by hannesaddec** [comment]
I found Poedit helpful

Mit TouchDown von meinem Android-Telefon gesendet (www.symantec.com)

-----Original Message-----
