### ISSUE TITLE
Upgrade Docker image to newer version of Python

### ISSUE THREAD

**Issue by owenlamont** [geopython/GeoHealthCheck#438]
**Is your feature request related to a problem? Please describe.**
The current Docker image is based on [Alpine Python 3.7](https://github.com/geopython/GeoHealthCheck/blob/e8585c642b89a590be0b7546aa8063b5579353f1/Dockerfile#L1) - and support for Python 3.7 ends on [27 June 2023](https://www.python.org/downloads/).

**Describe the solution you'd like**
I'd like the Docker image to be updated to be based on Python 3.10 or even Python 3.11 if the dependencies allow and the code base updated to be compatible with the selected version of Python.

**Describe alternatives you've considered**
You can ignore the Python support date but you expose your users to security risks to force them to use an unsupported Python - and I think it is likely to discourage potential contributors if they have to use an old/unsupported Python.

**Comment by justb4** [comment]
Thanks for heads up! Python 3.10/11 also has improved performance. 
Main issues are dependencies, both Python and native.
 For most projects moving away from Alpine to slim Debian/Ubuntu Docker images. 

See two strategies to upgrade Dockerfile:

- upgrade current Alpine Python image to 3.10/11
- move base image to Debian/Ubuntu (slim)  and then migrate Python to 3.10/11

PRs are highly appreciated. Other challenges: there are many outdated Python packages, mainly related to Flask, these will require code changes when upgrading.

 .
