### ISSUE TITLE
Broken link to /static/docs on geohealthcheck.osgeo.org

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#47]
First of all: great work you people are doing on GHC! Planning to use and possibly contribute in the coming time.

Don't know if this app belongs to this repo/project here, but I signal this anyway: http://geohealthcheck.osgeo.org/ has a broken link when clicking Help button: http://geohealthcheck.osgeo.org/static/docs/index.html. Possibly an idea to host the docs on https://readthedocs.org ? Is relatively easy. Hey, that could be my first contrib but one needs project admin rights! ... pff I now see, there is: http://geopython.github.io/GeoHealthCheck/

**Comment by tomkralidis** [comment]
@justb4 thanks for the report.  I manage http://geohealthcheck.osgeo.org/ and have updated the deployment to build docs (which was implemented in #31) so the link works now.

I'd like to get us on RTD at some point once the documentation matures.
