### ISSUE TITLE
Dependency broken on startbootstrap-sb-admin-2

### ISSUE THREAD

**Issue by ldgeo** [geopython/GeoHealthCheck#54]
On a fresh installation, i have a 404 on paver setup when it tries to get http://github.com/IronSummitMedia/startbootstrap-sb-admin-2/archive/v1.0.3.zip

It seems that the master branch of IronSummitMedia/startbootstrap-sb-admin-2 has been completely crushed recently, so no more link for 1.0.3 version.   

related issue :  https://github.com/ironsummitmedia/startbootstrap-sb-admin-2/issues/1

Is replacing **IronSummitMedia/startbootstrap-sb-admin-2** with **BlackrockDigital/startbootstrap-sb-admin-2** a good workaround ?

**Comment by tomkralidis** [comment]
@ldgeo thanks for the info per your suggestion.  Fixed in master.  Can you try re-installing and verify the install works now?
