### ISSUE TITLE
requirements.txt should include Sphinx PyPi package

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#57]
Standard setup via ``Paver/pavement.py`` will call ``sphinx-build`` to generate documentation. This requires PyPy package Sphinx to be present. Requirements are installed in ``pavement.py setup()`` via ``sh('pip install -r requirements.txt')``.  The current version of ``requirements.txt`` does not contain ``Sphinx`` (only ``requirements-dev.txt``). This caused an install error on a clean Ubuntu 14.04 system.

**Comment by tomkralidis** [comment]
@justb4 fixed in master.  Can you validate?

**Comment by justb4** [comment]
Looks good, I was just preparing a PR though...
