### ISSUE TITLE
Notifications: 'Still Failing' status may trigger too many emails

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#65]
If notification is enabled GHC will send email on status changes: e.g. ``Failing`` when a Resource fails, ``Fixed`` when it succeeds again. But when a Resource is e.g. out of order for a longer period the status ``Still Failing`` will be sent on each Run. In most uptime monitors  this status is never sent. In cases, e.g. when a server has multiple OWS services or many WWW:LINKs one may get flooded with emails that don't add anything that we already know. 

My proposal is to skip notification for the result ``Still Failing``: a Resource may be temporarily down. The first email ``Failing`` and a second ``Fixed`` would IMO be sufficient. We can derive that in between these statuses the Resource is ``Still Failing``. Another option is to make notification for this status configurable (default False), but I doubt that users will apply this. 

The fix is utterly simple, I can commit that, but maybe there were strong reasons for ``Still Failing`` notifications.

**Comment by tomkralidis** [comment]
The idea behind `Still Failing` takes after the Travis workflow where a failing build over numerous commits sends email like `Still Failing`. Having said this, getting flooded with email with the same messages can indeed be superfluous and annoying.

How about we change the default behaviour to not emit `Still Failing` messages unless `GHC_NOTIFICATIONS_VERBOSITY=True` type thing?  So if this config key exists and if it's `True`, then send `Still Failing` emails.  So users that really want this will apply it.  Thoughts?

**Comment by justb4** [comment]
Yes, we can do that. Like to hear other users' thoughts. ``GHC_NOTIFICATIONS_VERBOSITY`` could also serve as a flag for more fine-grained notifications such as performance degradation. In our setup I get so many (100's a day) emails as we couple multiple ``WWW:LINKs`` (e.g. WMS GetMaps for dynamic data) to a single OWS endpoint, both directly and via proxied HTTP-servers firewalls etc, as the latter could also impact services. So less verbosity is welcomed ;-). I can make a start.

**Comment by tomkralidis** [comment]
Sounds good @justb4! +1 for user feedback.  Interesting to hear using GHC `WWW:LINK` for dedicated WMS GetMap requests monitoring (the previously discussed custom plugin approach would really help for different types of tests, but that's for another ticket/day :) )

**Comment by justb4** [comment]
Yes, for full semantic response checking and Resource-organized monitoring we would need a combination of #18 and #19. E.g. individual WWW:LINK Resources should be able to be coupled to a 'parent' OWS Resource (#18 grouping) and, as e.g. WMS responses would respond false positive (HTTP 200) but with an Exception in XML text or ``inimage`` we need a variant of #19. For OWS-checking for the ``Exception`` keyword would suffice. These we can propose at the respective issues.

Back to this issue ``GHC_NOTIFICATIONS_VERBOSITY`` to en/disable ``Still Failing`` notifications would be easy to implement. I would say: let's go!

**Comment by tomkralidis** [comment]
+1!

**Comment by justb4** [comment]
Fixed and found working.
