### ISSUE TITLE
Move docs to readthedocs.org

### ISSUE THREAD

**Issue by justb4** [geopython/GeoHealthCheck#67]
/docs are now published manually to gh-pages. More effective is to use automated post-commit RTD (a.o. doc-versioning and PDF print).  http://docs.geohealthcheck.org will DNS-point to RTD.

**Comment by tomkralidis** [comment]
Done: http://geohealthcheck.readthedocs.io

@justb4 can you adjust the DNS?

**Comment by justb4** [comment]
Good! DNS done: a CNAME for docs.geohealthcheck.org to geohealthcheck.readthedocs.io. 

You need to set the CNAME ``docs.geohealthcheck.org`` in the RTD admin setting , see also http://docs.readthedocs.io/en/latest/alternate_domains.html.
