### ISSUE TITLE
Problems with using postgresql as the back end database

### ISSUE THREAD

**Issue by archaeogeek** [geopython/GeoHealthCheck#73]
Hi All,

I've got geohealthcheck happily running with the default sqlite backend but wish to switch to postgresql. I'm using postgresql 9.3 on an Ubuntu 16.04 server. The site starts OK but I get an error on adding the first site.

Procedure:
1) Install postgresql, create user for geohealthcheck, check it can log in to postgresql
2) Switch datatabase connection string in config-site.py to use postgresql
3) Run command paver create to create db and set up admin user
4) Start geohealthcheck locally (python app.py)- Geohealthcheck loads with empty list of sites
5) Login with admin user, go to add new site, pick standard URL
6) Geohealthcheck errors with the following:

`ProgrammingError: (psycopg2.ProgrammingError) argument of HAVING must be type boolean, not type timestamp without time zone
LINE 4: HAVING min(run.checked_datetime) ORDER BY run.checked_dateti...
               ^
 [SQL: 'SELECT run.identifier AS run_identifier, run.resource_identifier AS run_resource_identifier, run.checked_datetime AS run_checked_datetime, run.success AS run_success, run.response_time AS run_response_time, run.message AS run_message \nFROM run \nWHERE %(param_1)s = run.resource_identifier GROUP BY run.checked_datetime \nHAVING min(run.checked_datetime) ORDER BY run.checked_datetime ASC \n LIMIT %(param_2)s'] [parameters: {'param_1': 1, 'param_2': 1}]`

I've tested this on three separate instances and get the same result each time. Any thoughts?

Thanks

Jo

**Comment by justb4** [comment]
Not directly, my guess is that most installations use sqlite. SQLAlchemy should hide all differences among DBs but appearantly not. The error seems to come from querying `Run`. The error looks like this one:
http://stackoverflow.com/questions/27542471/error-argument-of-having-must-be-type-boolean-not-type-double-precision and is specified here:
https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/models.py#L117 expanding to `HAVING min(run.checked_datetime)` i.s.o. `HAVING min(run.checked_datetime) > 0`. Need to dive further into.

**Comment by justb4** [comment]
Issue confirmed. The above suggested fixes were incorrect. Appears harder than I initially thought to instruct SQLAlchemy to generate `HAVING min(run.checked_datetime) > 0` in PostgreSQL.

Thinking of this: why are `having` statements used? Like in the following:

```
    def first_run(self):
        return self.runs.having(func.min(Run.checked_datetime)).group_by(
            Run.checked_datetime).order_by(
                Run.checked_datetime.asc()).first()

    def last_run(self):
        return self.runs.having(func.max(Run.checked_datetime)).group_by(
            Run.checked_datetime).order_by(
                Run.checked_datetime.desc()).first()
```
I replaced this by:

```
    @property
    def first_run(self):
        return self.runs.order_by(
                Run.checked_datetime.asc()).first()

    @property
    def last_run(self):
        return self.runs.order_by(
                Run.checked_datetime.desc()).first()
```
@tomkralidis : this seemed to work, or am I missing something regarding the use of `having` and `groupby` ?

When the above worked, the next error came from https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/models.py#L145 and https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/models.py#L153. Replacing those lines with:

```
    def runs_to_json(self):
        runs = []
        for run in self.runs.order_by(Run.checked_datetime).all():
            runs.append({'datetime': run.checked_datetime.isoformat(),
                         'value': run.response_time,
                         'success': 1 if run.success else 0})
        return runs

    def success_to_colors(self):
        colors = []
        for run in self.runs.order_by(Run.checked_datetime).all():
            if run.success == 1:
                colors.append('#5CB85C')  # green
            else:
                colors.append('#D9534F')  # red
        return colors
```
fixed the errors.

Let me know and I can make a PR (or directly commit to `master`).

**Comment by tomkralidis** [comment]
thanks @justb4.  +1 for a PR

**Comment by justb4** [comment]
@archaeogeek can you test and hopefully close this issue?

**Comment by archaeogeek** [comment]
Seems to be sorted- I haven't spun up a clean instance though. I'll reopen if I get chance to do that and the issue reoccurs. Thanks for the speedy resolution :-)
