### ISSUE TITLE
When using postgresql paver create expects password of less than 10 characters

### ISSUE THREAD

**Issue by archaeogeek** [geopython/GeoHealthCheck#74]
Setting up the database using paver create, if you use postgresql as a back end (not sure if this affects other databases) then if you try to create an admin user with a password of more than 10 characters you get an error. Changing the back end user table to accept more characters and then re-running paver create fixes the problem. I don't think 10 characters is enough for a secure password.

**Comment by justb4** [comment]
This is due to a fixed column width of 10: https://github.com/geopython/GeoHealthCheck/blob/master/GeoHealthCheck/models.py#L170
We can expand, only issue are existing installations would require a DB-upgrade.

**Comment by tomkralidis** [comment]
How about changing to 255 chars?  Not sure we really need an elaborate migration path?

**Comment by justb4** [comment]
Yes, offcourse: existing installs would still have pw's of 10 or less, so forward compatible.

**Comment by tomkralidis** [comment]
Fixed in master.
