### ISSUE TITLE
Can't add tag to more than one resource

### ISSUE THREAD

**Issue by archaeogeek** [geopython/GeoHealthCheck#87]
I can create tags by editing a resource and adding a tag, and then saving the resource. However if I go to add the same tag to a new resource, GeoHealthCheck fails with the error:

`IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "tag_name_key"
DETAIL:  Key (name)=(premise) already exists.
 [SQL: 'INSERT INTO tag (name) VALUES (%(name)s) RETURNING tag.id'] [parameters: {'name': u'premise'}]`

(my tag name is premise)

I am using postgresql as the back-end database. 

I'm on commit a37d9d31b6ee09b2497b7b4973448bc79ae7ba87 which fixes #86 amongst other things. I did have trouble upgrading my database to include the tagging functionality, and basically created a new database with the additional tables in it, then restored the old database over the top. No errors were reported during this process.

**Comment by justb4** [comment]
Looks like same error I found:
https://github.com/geopython/GeoHealthCheck/issues/75#issuecomment-281076897

**Comment by justb4** [comment]
Think this is fixed with above commit. Can we close this issue?

**Comment by archaeogeek** [comment]
Sorry, didn't spot it had been fixed. I'll update it and test my install and close after that.

**Comment by archaeogeek** [comment]
Updated and checked, all seems to be working fine as far as I can tell. Thanks!
