### ISSUE TITLE
Enhancement: Allow differing notification emails per resource

### ISSUE THREAD

**Issue by archaeogeek** [geopython/GeoHealthCheck#88]
I would like to be able to specify a different notification email per resource so that site "owners" can be notified when their site is unavailable.  The email address could be stored in the database resource table and should be used as well as those set in config_site.py. If no email is specified for a resource then just the address(es) in config_site.py should be used.

**Comment by justb4** [comment]
Think this is duplicate of/contained in #15. Though the latter describes more elaborate facilities, we could start there with a simple owner-notification as you suggest. Ok to close this one and work further on #15?

**Comment by archaeogeek** [comment]
Indeed!
