### ISSUE TITLE
Issue with Flask-SQLAlchemy 2.2

### ISSUE THREAD

**Issue by elemoine** [geopython/GeoHealthCheck#89]
Flask-SQLAlchemy 2.2 was released on pypi a few days ago. But it looks like GeoHealthCheck is not compatible with that version. I get that error:

```
[2017-03-02 10:06:15,105] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 204, in home
    response = views.list_resources(resource_type, query, tag)
  File "./views.py", line 71, in list_resources
    response['resources'] = models.Resource.query.all()
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 498, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 78, in __call__
    return self.registry()
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/sqlalchemy/util/_collections.py", line 990, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2829, in __call__
    return self.class_(**local_kw)
  File "/opt/geohealthcheck/venv/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 144, in __init__
    track_modifications = app.config['SQLALCHEMY_TRACK_MODIFICATIONS']
KeyError: 'SQLALCHEMY_TRACK_MODIFICATIONS'
```

**Comment by justb4** [comment]
Confirmed (with `Flask-SQLAlchemy` 2.2). Thought setting `SQLALCHEMY_TRACK_MODIFICATIONS = False` in `site_config.py` could solve the `KeyError` above but then ran into other exceptions. For now the fix could be to pin  `Flask-SQLAlchemy==2.1`  in `requirements.txt` to get the app running and then work on upgrading the code, also for `Flask-Login` and `Flask-Babel`.

**Comment by bioslikk** [comment]
I had the same problem and like justb4 said downgrading  flask sql_alchemy to Flask-SQLAlchemy==2.1, resolved it for me. I was starting to feel desperate. Happy Coding!

**Comment by minhdanh** [comment]
I'm still having this problem with Flask-SQLAlchemy 2.2. Whether or not I set `SQLALCHEMY_TRACK_MODIFICATIONS` to True or False in app config, it always throws the above error. Will this be fixed?

**Comment by justb4** [comment]
@minhdanh GHC does not (yet) work with Flask-SQLAlchemy 2.2 (see above, more issues than the `KeyError`), so best is to stick (e.g. via `virtualenv`) with 2.1. It will be fixed but I cannot give timeframe now.

**Comment by minhdanh** [comment]
Ok. Sure. Thanks for the update

**Comment by Joyii** [comment]
did anyone solve the same problem?please comment me! thx!

**Comment by justb4** [comment]
On 03-06-17 21:02, Joyii wrote:
> did anyone solve the same problem?please comment me! thx!
Please read the above thread: for now there should not be a problem if 
you use Python virtual env, as is recommended in general, or more 
recent: GHC via Docker. But we are open for suggestions, PRs!

**Comment by punitjain1989** [comment]
I was having the similar issue. I downgraded SQLAlchemy to 2.1, but the issue still persists. Following is the content from the requiremens.txt

Flask==0.12.2
Flask-SQLAlchemy==2.1
gunicorn==19.7.1
psycopg2==2.7.4
flask-restplus
flask-cors==3.0.3
six==1.11.0
pyyaml==3.12
requests==2.18.4
google-auth==1.4.1
google-auth-oauthlib==0.2.0

PS - I am getting this issue on google cloud, but the same works fine in my local environment. Any advice on what could go wrong?  Thanks in advance!

**Comment by bioslikk** [comment]
I never used GeoHealthCheck but had a similiar error like @elemoine had. The @justb4's solution didn't work for you ?

**Comment by punitjain1989** [comment]
Thank you for your reply. I figured out the issue was something else. I created a global object of SQLAlchemy and at the time of initialization in main.py, it was not getting initialized. Eventually I had to do something like the following:

app = Flask(__name__)
    db.init_app(app)              ---> _Just this didn't work_ [Not sure why]
    **db.app = app**

**Comment by proximadata** [comment]
What is the eventual solution? I tried 2.2, had this exception. I tried 2.1, still the same. I tried db.app = app, no result. What to do, please help!

**Comment by vincentdione** [comment]
python alchemy.py 
/usr/local/lib/python3.5/dist-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in 

the future.  Set it to True or False to suppress this warning.
Hello Please i need a help. i am a beginner to Flask and i have this problem. 

 'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "alchemy.py", line 14, in <module>
    class Example(db.Model):
  File "alchemy.py", line 16, in Example
    id=db.Column('id',db.Integer,primary_Key=True)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/schema.py", line 1289, in __init__
    "Unknown arguments passed to Column: " + repr(list(kwargs)))
sqlalchemy.exc.ArgumentError: Unknown arguments passed to Column: ['primary_Key']

**Comment by vincentdione** [comment]
Hello Please i need a help. i am a beginner to Flask and i have this problem.
My Best regards!

**Comment by Abdulkereem** [comment]
> Hello Please i need a help. i am a beginner to Flask and i have this problem.
> My Best regards!

anyone with the idea on how to fix this error

**Comment by SergSm** [comment]
same error when doing this tutorial https://realpython.com/flask-connexion-rest-api-part-2/

**Comment by Reshaniresh** [comment]
anyone found the solution, am using Flask-SQLAlchemy 2.1, but still facing the issue.What to do??please response me..
Thanks,

**Comment by boulabiar** [comment]
> same error when doing this tutorial https://realpython.com/flask-connexion-rest-api-part-2/

The solution that worked for me was this:
https://stackoverflow.com/a/68675971/215263
