### ISSUE TITLE
Access resources requiring authentication

### ISSUE THREAD

**Issue by samperd** [geopython/GeoHealthCheck#9]
Is there a way to access resources requiring authentication?

**Comment by hannesaddec** [comment]
What kind of authentication are you referring to ? HTTP, Cookies, SSL, Shibboleth OpenID, CAS?

**Comment by justb4** [comment]
At least HTTP Basic Auth is used a lot, that would be a start. I take it that you need the ability to add credentials for a `Resource` URL? You could try to encode it in the URL like `http://username:password@example.com/`, not sure this will work in GHC, but also exposes creds via UI.

So, good point: could start adding optional user/password fields for a `Resource`.

**Comment by justb4** [comment]
Fixed via #259 , available on https://demo.geohealthcheck.org/

**Comment by samperd** [comment]
@justb4, thanks so much for considering this feature in the latest stantec sponsored development activity.

**Comment by justb4** [comment]
@samperd yes, you opened this a very long time ago! Does the current implementation work for you?

**Comment by justb4** [comment]
We are quite far, need to await Py2->Py3 migrate to use latest OWSLib with fixes for at WFS, CSW etc.

**Comment by borrob** [comment]
With the py3 migration fixed in #280: is there more to do for this issue?

**Comment by justb4** [comment]
We need to upgrade OWSLib from 0.17.0 to the latest version: https://github.com/geopython/OWSLib/releases (now 0.18.0), which should fix Resource auth for WFS (this issue) and some WFS3 fixes. Mainly quite some testing needed.

**Comment by borrob** [comment]
With PR #312 there is an update to OWSLib 0.19.

**Comment by justb4** [comment]
And now even to OWSLib 0.20.o. Want to first bring out 0.8.0 and quickly move to 0.8.1 for this one and related PRs.

**Comment by justb4** [comment]
Closing: via #333 : OWSLib is upgraded to 0.20.0, so Auth Headers should work with WFS and TMS as well. Please open specific issues for Auth problems/features.
